### ISSUE TITLE
Segmentation Fault (Core dumped)

### ISSUE THREAD

**Issue by Vishal2188** [HyeongseokSon1/SRFeat#10]
Hi...
When I evaluate the model using pretrained model .npz files. I got error called Segmentation fault (core dumped). How can I solve this issue?

**Comment by HyeongseokSon1** [comment]
I cannot analyze the specific reason from the text.
But I guess that the pretrained model cannot be loaded in recent versions of Tensorflow (>=1.10).
If you use these Tensorflow, please try the code in the lower version of Tensorflow.
