### ISSUE TITLE
aug_data_div2k.m

### ISSUE THREAD

**Issue by lingwei0816** [HyeongseokSon1/SRFeat#12]
Thank you for your code! When I run the matlab code 'aug_data_div2k.m',there exits a issue:Error using imwrite (line 454)
Unable to open file "E:\home\Image\process\SR\DIV_dataset\DIV2K\DIV_train_cropped\GT\013_1.png" for writing.
You might not have write permission.

Error in aug_data_div2k (line 52)
        imwrite(subim_label2, fullfile(savepath,'GT',[filepaths(i).name(1:end-5) '_' num2str(do_write)
        '.png']));
how can I solve this issue?

**Comment by HyeongseokSon1** [comment]
Please try to manually make all folders, which belong to the path, because the code do not include mkdir.

**Comment by lingwei0816** [comment]
OK,Thank u for your reply.
