### ISSUE TITLE
problem in model

### ISSUE THREAD

**Issue by crystaldtw** [HyeongseokSon1/SRFeat#9]
Recently I read your code and I want to know why SRGAN_d2 function is defined like that. 
I hope that you can solve my problem,thank you !

**Comment by HyeongseokSon1** [comment]
SRGAN_d2 is fully convolutional discriminator (a.k.a patch discriminator) for the additional experiment in the supplementary material.
We reported there is no significant gain from the structure.
And the network is not used in the codes in this repository.
